/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Homework;

import Homework.run.Runner;
import Homework.utilities.MyLogger;


public class App {
    public static void main(String[] args) {
        MyLogger.init();
        Runner runner = new Runner();
        runner.start();
    }

}
